### ISSUE TITLE
ErrorType: 3, Error occurred during evaluation: Unexpected token } 

### ISSUE THREAD

**Issue by nguyen-tam** [codemanki/cloudscraper#1]
Error occurred during evaluation: Unexpected token } when crawling a site with CloudFare protection. Seem they has changed their js :(

**Comment by nguyen-tam** [comment]
Here is the url : http://kissmanga.com/

**Comment by codemanki** [comment]
@nguyen-tam hey. Thanks for reporting this. For sure they changed something. I will take a look asap.

**Comment by nguyen-tam** [comment]
@codemanki The site has remove CloudFare anti-bot. So I can't test this error again. But it may comes from this line : challenge = challenge[1];

I think if site has more than 2 settimeout function, it may cause the bug.

**Comment by codemanki** [comment]
@nguyen-tam yeap, you are absolutely right. It has several setTimeout functions and regexp to extract the main one fails. I already fixed this part, but it seems that they introduced some additional checks on server side, and it throws 500 error. I will take a look at it today.

**Comment by codemanki** [comment]
I will keep this issue open to track progress

**Comment by codemanki** [comment]
Issue was fixed, new version is released.

**Comment by nguyen-tam** [comment]
Thanks. But when I tested the site return messages below, did they change their server side code ?
<body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

    </body>

**Comment by nguyen-tam** [comment]
I think jschl_answer is wrong
when I tracked the url should be but if I check with your script, jschl_answer is -6785
cdn-cgi/l/chk_jschl?jschl_vc=c73f4c3b681b190e6cefdd50fba9e606&jschl_answer=95416093

**Comment by codemanki** [comment]
@nguyen-tam i tried replacing `(eval(challenge) + response.request.host.length) ` with random ints, and apparently when answer is wrong cloudflare returns same page with challenge.

**Comment by nguyen-tam** [comment]
You're right. So they've check something at server side ?

On Thu, Jan 22, 2015 at 3:04 AM, Oleksii Sribnyi <notifications@github.com>
wrote:

> @nguyen-tam <https://github.com/nguyen-tam> i tried replacing (eval(challenge)
> + response.request.host.length) with random ints, and apparently when
> answer is wrong cloudflare returns same page with challenge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemanki/cloudscraper/issues/1#issuecomment-70911083>
> .
>



-- 
Nguyen Dinh Tam
Mobile: +84 988913843
Email: t <nguyendinhtam@inno-bee.com>amndrok@gmail.com

**Comment by codemanki** [comment]
@nguyen-tam not really. it seems that request lib sends some invalid/excessive data or improperly follows last 302 redirect.
 i played with it yesterday and came to this conclusion. i will continue investigation today.
