### ISSUE TITLE
Cloudflare community

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#100]
Pop a bag of :popcorn: and read this: https://community.cloudflare.com/t/5-seconds-javascript-challenge/63062/8
He's scared. :rofl:

**Comment by pro-src** [comment]
@codemanki Cloudflare's employees are collaborating with us :rofl: 

Check @buro9 out, he's watching the repo, just cloned, and even fixed a link in the README.md
I'm serious. The commit was like 15mins ago! :rofl:

**Comment by buro9** [comment]
I do work for Cloudflare, wasn't watching this repo. But used to watch the python one and saw a comment there mentioning this. I was curious as to whether this is a new technique and it's not, but thought I'd fix your broken help link :)

Happy to answer questions if you have any, but not looking to disrupt your work. Whilst I'm not in the team that deals with the JavaScript challenge I know of no cat and mouse game with this or the python code. This is merely intellectual curiosity and trying to be helpful.

**Comment by pro-src** [comment]
@buro9 You're awesome! Just curious, do you have any insight into this [comment](https://github.com/Anorov/cloudflare-scrape/issues/60#issuecomment-225375780). Would you agree that the javascript challenge's code addition, at that time, served no other purpose other than to foil attempts at scraping? Also, could you recommend any support documents that might by of interest? :D

**Comment by buro9** [comment]
I don't have insight into motive behind changes and don't wish to speak uninformed on behalf of whomever did the change at that time.

**Comment by pro-src** [comment]
Fair enough. Thanks

**Comment by pro-src** [comment]
@buro9 Do you know anything that you'd care to comment about???
