### ISSUE TITLE
Rewrite tests to spy on real requests using a test server

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#104]
This is how the request library does their unit testing and makes thing simpler as we won't have to ensure that the fake request behavior exactly mimics the real request behavior. All tests were passing on the v3.0.0 branch but, due to the fake request callback behavior not exactly mimicking the real request callback behavior, cloudscraper didn't work properly with request-promise. This should make things more maintainable and provide more reliable tests. I'm currently in the process of modifying `test/helper` to callback the way real requests do but it's over complicated by the test framework. At some point, we really should use a test server.

**Comment by pro-src** [comment]
#103

**Comment by pro-src** [comment]
@codemanki, what do you think about the following sample?
```js
describe('Cloudscraper', function() {
  var sandbox;
  var Request;
  var router = undefined;

  var app = express();

  app.use(function (req, res, next) {
    router(req, res, next);
  });

  app.listen(0, '127.0.0.1', function () {
    var baseUrl = 'http://127.0.0.1:' + app.address().port;

    // Use the baseUrl option to shorten uri
    cloudscraper.defaultParams.baseUrl = baseUrl;

    // Update the default params
    helper.defaultParams.baseUrl = baseUrl;
    helper.defaultParams.uri = '/test';
  });

  beforeEach(function () {
    sandbox = sinon.createSandbox();
    // Prepare a Request spy for each test
    Request = sandbox.spy(request, 'Request');
    // Create a new router for each test
    router = new express.Router();
    // setTimeout should be properly stubbed to prevent the unit test from running too long.
    this.clock = sinon.useFakeTimers();
  });

  afterEach(function () {
    sandbox.restore();
    this.clock.restore();
  });

  it('should return error if it was thrown by request', function (done) {
    router.get('/test', function (req, res) {
      res.connection.write(
          'HTTP/1.1 500 Let\'s ruin that response!\r\n' +
          'Content-Type: text/plain\r\n' +
          'Transfer-Encoding: chunked\r\n\r\n'
      );
      res.end();
    });

    var promise = cloudscraper.get('/test', function (error) {
      expect(error).to.be.instanceOf(errors.RequestError);
      expect(error).to.have.property('error').that.is.an('error');
      expect(error).to.have.property('errorType', 0);

      expect(Request).to.be.calledOnceWithExactly(helper.defaultParams);
    });

    expect(promise).to.be.rejectedWith(errors.RequestError).and.notify(done);
  });

  it('should return error if captcha is served by cloudflare', function(done) {
    var html = helper.getFixture('captcha.html');

    router.get('/test', function (req, res) {
      res.status(503).send(html).end();
    });

    var promise = cloudscraper.get('/test', function (error, response, body) {
      // errorType 1, means captcha is served
      expect(error).to.be.instanceOf(errors.CaptchaError);
      expect(error).to.have.property('error', 'captcha');
      expect(error).to.have.property('errorType', 1);

      expect(Request).to.be.calledOnceWithExactly(helper.defaultParams);

      expect(response.statusCode).to.be.equal(503);
      expect(body).to.be.equal(html);
    });

    expect(promise).to.be.rejectedWith(errors.CaptchaError).and.notify(done);
  });
});
```

**Comment by codemanki** [comment]
@pro-src that is an interesting idea. I was actually always doing testing like this with mocks and stubs. I think it would make sense to have a couple of tests like this, to exclude a scenario with callback bug, but frankly speaking, it also gives me a feeling that we would need to somewhat replicate the cloudflare's logic on out test server side. 
🤔  but indeed it would make tests lighter and cleaner. I think I could introduce this approach for 1-2 test for 3.0.0 release and then if it works well just rewrite the rest to use a fake server.

**Comment by pro-src** [comment]
I can't get this to work for multiple requests in a single test. I think it's ***mocha*** and/or ***sinon-timers*** causing the problem. _I haven't tried this on CI_. When I attempt to debug this locally, the `setTimeout` statement in cloudscraper never calls back. `setTimeout` is executed but it just never actually calls it's callback. I've tried increasing the timeout with `this.timeout(100000)` and removing/changing `this.tick(...)` but nothing seems to work.

**Comment by pro-src** [comment]
@codemanki, I don't currently have a solution for this but here a minimum test case:
```js
var express = require('express');
var sinon = require('sinon');
var request = require('request-promise');

var app = express();
var server;

app.get('/test', function() {
  console.log('Sending response');
  res.status(200).end();
});

function cloudscraper(url, i, callback) {
  console.log('cloudscraper call ' + i);
  if (i < 2) {
    console.log('Sending request ' + i);
    request.get(url).then(function() {
      console.log('Received response ' + i);
      setTimeout(cloudscraper, 5000, url, ++i, callback);
    });
  }
  else {
    console.log('callback, i = ' + i);
    callback();
  }
}

describe('cloudscraper', function() {
  before(function (done) {
    server = app.listen(0, '127.0.0.1', done);
  });

  beforeEach(function() { this.clock = sinon.useFakeTimers(); });
  afterEach(function() { this.clock.restore(); });

  it('should callback', function(done) {
    var url = 'http://127.0.0.1:' + server.address().port + '/test';
    cloudscraper(url, 0, done);
    this.clock.tick(30000);
  });
});
```

I think Mocha is to blame and not sinon-timers. I'm pretty sure it's due to Bluebird waiting until the next event loop but Mocha shouldn't be fumbling the ball with that. So, I am trying to figure this out but if I start work on a PR, I'll let you know in advance. Feel free to take this.

**Comment by codemanki** [comment]
@pro-src thanks!

**Comment by pro-src** [comment]
@codemanki, welcome. This is the issue: https://github.com/sinonjs/sinon/issues/1739

**Comment by pro-src** [comment]
@codemanki, It seems obvious now that the best way to solve this problem is just to stop using sinon-timers and reduce the cloudflareTimeout in tests to something like ~1ms. I'm going to start working on this.

**Comment by pro-src** [comment]
:grey_question:
