### ISSUE TITLE
Ensure match isn't null for proper error handling

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#112]
This will bypass the error handling and result in an uncaught exception, potentially terminate the nodejs process, and/or not callback properly. It's unlikely to ever be null (other errors would occur first) but it should still be checked the same as other matches.
https://github.com/codemanki/cloudscraper/blob/28647b403aa267d22e6c3ab2839ec42296f91311/index.js#L209

**Comment by codemanki** [comment]
Fixed by https://github.com/codemanki/cloudscraper/pull/113
