### ISSUE TITLE
Possible to login into website?

### ISSUE THREAD

**Issue by dasmikko** [codemanki/cloudscraper#12]
Hi!

What I'm asking is, I'm making a small REST API for a website, and I was wondering, is it possible to do a POST to a login page, and save the session cookie to that website, and keep being logged in for the rest of the session?

Hope it makes sense!

**Comment by codemanki** [comment]
Hey there. I'm pretty sure it is possible in this way:
```javascript
cloudscraper.post('http://site.com/login', {login:'test', password:'test'}, function(err, body, response) {
  console.log(response.request.headers.cookie);
});
````

Let me know if this works fine for you. If not, we will find some other solution :)
