### ISSUE TITLE
Increase NPM package quality score to 100%

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#128]
We're almost there but we can improve this further!

Quality Score: 83%

* Tests (0.6 === 100%)
* Health 100%
* Carefulness 92%
* Branding 0%

[As returned from npmjs.com's api ](https://api.npms.io/v2/package/cloudscraper)  [ [tree viewer](https://jsoneditoronline.org/?id=6e4cf838ad8e44a585e4eac7e4fc9e9c) ]
```json
{
  "evaluation": {
    "quality": {
      "carefulness": 0.9199999999999999,
      "tests": 0.6,
      "health": 1,
      "branding": 0
    }
}
```

There are at least 4 badges in the master branch's README.md so the branding will be 60% when that is published. In order to get the last 40% in branding, the homepage can't be this github repo (https://github.com/codemanki/cloudscraper).

I would like to use github-pages on a `gh-pages` branch and change the `package.json`'s homepage to point to it (codemanki.github.io/cloudscraper). This will result in a total branding score of 100%.

If you wanted to create an orphaned branch and push it, I could send a PR for that. Just let me know.
```sh
cd cloudscraper
git checkout --orphan gh-pages
git rm -rf .
rm '.gitignore' '.github'
echo "#Placeholder" > README.md
git add README.md
git commit -a -m "Initial Commit"
git push origin gh-pages
```

The last thing necessary to get an overall quality score of 100% is the carefulness. There must be an npm ignore section or explicitly included files in `package.json` to get the missing (0.08) in carefulness.

Those two things will increase the overall quality by 17% and get cloudscraper a full score.

**Comment by pro-src** [comment]
@codemanki, I now see cloudscraper when I search for "cloudflare" on npmjs.com!

**Comment by codemanki** [comment]
Oh my. I didn't even know that you should do a SEO in npm. Crazy days :D

**Comment by pro-src** [comment]
Well, typically it's not necessary. If the project is modern, very active, and maintained properly, it naturally has a high score. However, double checking this to ensure that the package isn't several pages deep for the most common search terms is a excellent idea and as the package maintainer, things like quality and maintenance are completely under your control.

**Comment by pro-src** [comment]
@codemanki, I was wrong! I'm sure am glad I was too! Check it out: https://www.npmjs.com/search?q=cloudflare

It's the second result! It would be the first listing but the exact name match is unbeatable. We've achieved 100% quality and 100% maintenance!!! :tada: :champagne: :sparkle:
