### ISSUE TITLE
Issue with captcha

### ISSUE THREAD

**Issue by Roguyt** [codemanki/cloudscraper#13]
Hello,
I have an issue with cloudscraper, i get an error code 1, when i try to get a page from hltv.org.
But i can get the source without any problem when i just use request.
Any ideas ?

Thanks for your job

**Comment by codemanki** [comment]
Hey. Thanks for reporting this. Issue was that page hltv.org had recaptcha in it and cloudscraper was detecting it as CF page protected by captcha. I've improved the detection and released version `1.2.2`. Let me know if the fix works for you!

**Comment by Roguyt** [comment]
Hey,
Just checked it works perfectly !
Thanks m8
