### ISSUE TITLE
Add missing contributors to readme

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#130]
A couple guys aren't mentioned: https://github.com/codemanki/cloudscraper/graphs/contributors
Please remove the special attribution to myself so as not to devalue the other contributions. The way I see it is every contribution, no matter how small, matters just as much. Plus one line of code can be a very big deal.

**Comment by pro-src** [comment]
@codemanki, this should be removed from the README:
> Not everything is supported however, for example http methods other than GET and POST. If you wanted to request an image in binary data you could use the encoding option:

**Comment by codemanki** [comment]
>Please remove the special attribution to myself so as not to devalue the other contributions. 

I'm really grateful for what you did and how much work and time you invested in cloudscraper. And this was the way to show my appreciation. 
I will add missing people to the readme and if you strongly wish, i will remove the attribution to you. Please let me know

**Comment by pro-src** [comment]
Ya, I'm sure. It'll go to my head and it's too big already. :stuck_out_tongue_closed_eyes:
