### ISSUE TITLE
[Bug] [V3] Option json

### ISSUE THREAD

**Issue by Revadike** [codemanki/cloudscraper#132]
Setting `json` option property to true, seems to return the string `[object Object]` as `body`.

From `node-request` README:
```
json - sets body to JSON representation of value and adds Content-type: application/json header. Additionally, parses the response body as JSON.
```

**Comment by codemanki** [comment]
@Revadike same as for https://github.com/codemanki/cloudscraper/issues/134, would you please share the code?
I've just tried `cloudscraper.get({url:'https://iload.to/', json:true})` and it worked fine for me returning body as string

**Comment by Revadike** [comment]
Well, the fact that the body is a string and not a parsed JSON object already indicates the `json` option doesn't work as intended.

**Comment by codemanki** [comment]
@Revadike oh, i see.
`cloudscraper.get({url:'http://country.io/continent.json', json:true})` this results in the `[object Object]`. But if i remove the json flag, it returns proper object

**Comment by codemanki** [comment]
@pro-src it looks like before recent changes clouscraper always expected either Buffer or String as a body, but request's documentation explicitly states that : `The third is the response body (String or Buffer, or JSON object if the json option is supplied)`

So i would suggest to check for `options.json` in `processResponseBody` method (https://github.com/codemanki/cloudscraper/blob/master/index.js#L298) and do not cast body to string if it is `typeOf(body) === 'object'` ( e.g. it is json). What do you think about this fix?

**Comment by codemanki** [comment]
@Revadike while we prepare the fix, you could just remove `json: true` and it will continue working as expected.

**Comment by pro-src** [comment]
@codemanki, sounds good. The body should always be an object and never a string because the encoding option is set to `null` but the additional check for sanity is a good idea.

**Comment by pro-src** [comment]
@codemanki, also note that this has nothing to do with v3. It was always an error but we get to fix it now. :smile:
