### ISSUE TITLE
Can't update to newer version

### ISSUE THREAD

**Issue by abuyasin82** [codemanki/cloudscraper#141]
I'm trying to update the packet to the newer version 3 but still won't upgrade the 2.0.1 version

**Comment by abuyasin82** [comment]
never mind, I had to remove the packet and install it again to get the new version

**Comment by codemanki** [comment]
@abuyasin82 i have just released 3.1.0 with a fresh fix for CF challenge. You might want to update the package once again

**Comment by abuyasin82** [comment]
thanks man the new update works as a clock
