### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by Netskyes** [codemanki/cloudscraper#142]
Hey, I'm getting the following error:
errorType: 3, error: 'Error occurred during evaluation: Unexpected end of input' 

I believe since 2 days ago, the challenge has been updated?

**Comment by pro-src** [comment]
@Netskyes It's already been updated. Try `npm install --save cloudscraper@3.1.0`

**Comment by Netskyes** [comment]
@pro-src I did, but still getting that error :)

**Comment by Netskyes** [comment]
Nevermind seems like it was cached, thanks for the help :)

**Comment by Netskyes** [comment]
Hey, noticed a new issue now, for some reason a page that should return total of 3mb body, returns 6.9mb now.

**Comment by pro-src** [comment]
@Netskyes Hmm, so long as the page being requested is returned, I doubt that it's an issue with cloudscraper but if you'll put it in a pastebin I'll check it out for ya.

**Comment by pro-src** [comment]
@Netskyes Also, it would be better if you closed this issue since it's been solved and open a new one. :)

**Comment by Netskyes** [comment]
@pro-src Sure, thank you! :)
