### ISSUE TITLE
Cloudflare challenge loop

### ISSUE THREAD

**Issue by elpaxel** [codemanki/cloudscraper#148]
20 min ago I've start getting: Cloudflare challenge loop error. I think it's because of "need to update ASAP":

@codemanki, I meant to make that case insensitive. It should be `.replace(/^\s*[a-z0-9_$]+\s*[=.].+/gmi, '')` but it mostly doesn't matter. What does matter is that these replacements can fail silently. If they fail silently, you'll get a Cloudflare challenge loop. I think we should update this to throw a ParserError if replacements fail because that means the challenge has changed and we need to update ASAP. Whereas the challenge loop doesn't clearly identify the cause.

_Originally posted by @pro-src in https://github.com/codemanki/cloudscraper/pull/140_

**Comment by codemanki** [comment]
@elpaxel thanks for reporting this issue. Will look into it in a couple hours once i'm behind laptop

**Comment by pro-src** [comment]
@elpaxel, would you mind try the fix in that PR?

@codemanki This isn't due to replacements failing but that comment is still kinda relevant. See my comment in #149

**Comment by ArnaudPiroelle** [comment]
@pro-src it works ! I confirm ;)

**Comment by codemanki** [comment]
The fix by @pro-src has been applied and i just released 3.2.0. Thank you @pro-src  :) 🚀
