### ISSUE TITLE
DDoS

### ISSUE THREAD

**Issue by 3DSX** [codemanki/cloudscraper#157]
How can i use this for DDoS a website with UAM on?

**Comment by pro-src** [comment]
@3DSX First of all, that is not and never will be the intended purpose of cloudscraper.

Quoting from the article linked in #100:

***Judge said:***
> In general the script still has to wait 5 seconds, so unless they have a large amount of hosts, it won’t be as effective of a DDOS attack. Getting such a volume of computers to do this (mind you, this is a Node script that needs dependencies and setup) would require a large botnet or renting servers from cloud providers, both of which are hard to do without being caught.

> If you do end up seeing your site taken down due to this, instead you should try a Firewall rule setting security to “challenge” (captcha).

Quoting from: http://ddosattackprotection.org/blog/is-ddos-illegal/

> Under the guidelines of the law, those found guilty can face up to 20 years in prison.

You'll find similar laws in other countries such as the UK: http://www.nationalcrimeagency.gov.uk/1256-ddos-attacks-are-illegal

**Comment by pro-src** [comment]
@3DSX Please close this issue and refrain from asking similar questions. Thanks
