### ISSUE TITLE
error 1008, page in wiki is wrong

### ISSUE THREAD

**Issue by cagnulein** [codemanki/cloudscraper#16]
If i try to scraping this url http://vcrypt.net/shield/HSXWXJKcvcJTgm4AAGhG9db4LFAyMO6dlnaQCpm65PSHoDhUM1tZWG_ppl_LgwpDPRbC it returns error 2 - 1008.
I'm tring to understand which is the meaning of this error but the page linked into the wiki of this project is wrong. Could you please help me?
Thanks

**Comment by codemanki** [comment]
Looks like your ip was banned. Not related to cloudscraper:
[Error 1006, 1007 & 1008 Access Denied: Your IP address has been banned](https://support.cloudflare.com/hc/en-us/articles/200171886-Error-1006-1007-1008-Access-Denied-Your-IP-address-has-been-banned)
