### ISSUE TITLE
No longer a port of cloudflare-scrape

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#166]
Cloudscraper :1st_place_medal: 

> This library is a port of python module cloudflare-scrape with couple enhancements and test cases ;) . All grats to its author \m/ 

While this was originally a port of cloudflare-scrape in 2014, Cloudscraper has diverged to the extent that I feel like the README is under selling it. 

Now, lets give credit where it's due. The author of cloudflare-scrape was one of the first to publish a library to bypass IUAM. Kudos to him. Now that we've done that. Can we change the README message about cloudflare-scrape to something more subtle? I would move it down to the very bottom of the README under a "Credits" header, "Similar Projects" header, or remove it entirely. 

Lets put something that promotes Cloudscraper in that attention grabbing spot. Something similar to the following: "Bypassing every version of Cloudflare's Anti-Scrape shield since 2014".

Just an opinion. Can I get a :+1:?

**Comment by codemanki** [comment]
>every version
Hope they won't call this a challenge :D 

Overall this sounds like a reasonable change. I will move that text to the bottom and will rephrase it  but will keep all the credits and kudos. Thank you for taking care of such things and cloudscraper ❤️

**Comment by pro-src** [comment]
> Hope they won't call this a challenge :D

Ditto. I didn't really put that much thought into it, lets not provoke them. :sweat_smile:
