### ISSUE TITLE
challengesToSolve is not enforced for redirect challenges

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#168]
I've never encountered this type of challenge so I don't know if it's intentional or not. If these are served consecutively, I imagine that it could cause a loop.
https://github.com/codemanki/cloudscraper/blob/e0727c07a3d58bdc8f15417b5a4a1ce0980a2b72/index.js#L303

Edit: <strike>It's clear that it wasn't initially intended.</strike>

commit https://github.com/codemanki/cloudscraper/commit/971556fc9989ba4408ae401609a81c017852c206#diff-168726dbe96b3ce427e7fedce31bb0bcR120 (Added by #66)
commit https://github.com/codemanki/cloudscraper/pull/66/commits/52334665860071bf2bde2e0a5632d3e439181061#diff-168726dbe96b3ce427e7fedce31bb0bcL120 (Added by #66

<strike>I think the latter was meant to check `isTargetPage` instead of `isChallengePresent`.</strike>
I finally found the right commits and it's not clear to me. :roll_eyes: :smile:

**Comment by codemanki** [comment]
@pro-src hey. The initial idea was to only use `challengesToSolve` when actual challenge is solved, so we don't solve more than `X` in row. I guess if it is just a redirect then it is not considered as a real challenge.

**Comment by pro-src** [comment]
Isn't it safe to remove that function entirely? I think this library is the only one that still supports it.

**Comment by pro-src** [comment]
Is it safe to remove that function entirely?

**Comment by codemanki** [comment]
Then we kill it, yes
