### ISSUE TITLE
Captcha error returned

### ISSUE THREAD

**Issue by newt-sc** [codemanki/cloudscraper#176]
Trying the lib for https://movcr.cc is returning captcha error. First reported in: https://github.com/Anorov/cloudflare-scrape/issues/217#issuecomment-478693967

**Comment by newt-sc** [comment]
Should I use those headers or get the ones from my own browser?

**Comment by pro-src** [comment]
You can impersonate me, it's cool. :smile:

**Comment by newt-sc** [comment]
Cool I am closing the issue.
