### ISSUE TITLE
problem with response

### ISSUE THREAD

**Issue by gustavomauricio** [codemanki/cloudscraper#189]
After the request the error comes as null but it doesnt return me a json, the response.body is just `<Error><Message>An error has occurred.</Message></Error>`. Any idea what the issue might be?

**Comment by pro-src** [comment]
@gustavomauricio I'm guessing you figured this out hence why you closed the issue. For information, that response body seems to imply that the error wasn't due to cloudscraper but rather some API or server related error. Also, if `error === null`, the error didn't come from cloudscraper. Good luck.
