### ISSUE TITLE
Challenge evaluation failed due to unexpected token

### ISSUE THREAD

**Issue by Majored** [codemanki/cloudscraper#190]
I'm receiving the following error while using Cloudscraper; only started happening in the last day or two. I've tested this with two different sites protected with CloudFlare, and receive the same message (haven't had time to test any more).

Sorry for the lack of information on this issue; just wanted to inform and/or see if this is an issue isolated on my end?

```Unhandled rejection ParserError:
### Cloudflare may have changed their technique, or there may be a bug.
### Bug Reports: https://github.com/codemanki/cloudscraper/issues
### Check the detailed exception message that follows for the cause.

SyntaxError: Challenge evaluation failed: Unexpected token |
    at solveChallenge (C:\Assets\Storage\Development\cf-bypass\node_modules\cloudscraper\index.js:248:21)
    at Timeout._onTimeout (C:\Assets\Storage\Development\cf-bypass\node_modules\cloudscraper\index.js:179:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)```

**Comment by codemanki** [comment]
Hey! Thanks for reporting this. Could you please share the urls you are failing to scrape? If you don't want to do it here, just send me an email at `me@codemanki.com`

**Comment by balimeister** [comment]
Same here!

URL: http://rmz.cr/

Unhandled rejection ParserError: 
### Cloudflare may have changed their technique, or there may be a bug.
### Bug Reports: https://github.com/codemanki/cloudscraper/issues
### Check the detailed exception message that follows for the cause.

SyntaxError: Challenge evaluation failed: Unexpected token |

**Comment by pro-src** [comment]
Cloudflare added an atob polyfill: `e("ZG9jdW1l") === "docume"`
[cf-debug](https://npmjs.com/package/cf-debug) output: https://gist.github.com/pro-src/08f53dc5c4504cf4981948b49831e553

@Venomous

**Comment by pro-src** [comment]
@Majored If you like to confirm this fixed:
```sh
cd your-project
npm i --save "git://github.com/pro-src/cloudscraper.git#190_latest_challenge"
# The following command will remove node_modules and do a fresh install 
npm ci
```

**Comment by codemanki** [comment]
Thank you @pro-src ! `3.8.0` was just released
