### ISSUE TITLE
CaptchaError: captcha on v3.9.1

### ISSUE THREAD

**Issue by grasssnake123** [codemanki/cloudscraper#195]
CaptchaError: captcha on v3.9.1
code:
```
var cloudscraper = require('cloudscraper').defaults({
  headers: {
    'Connection': 'keep-alive',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Language': 'en-US,en;q=0.9'
  }
});
var uri = 'https://subscene.com';
cloudscraper.get(uri, function (error, response, body) {
  if (error) {
    throw error;
  }
  console.log(body);
});
```
error:
```
node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^
CaptchaError: captcha
```

**Comment by pro-src** [comment]
@grasssnake123 Would like to try my PR to see if it resolves your issue? Mind you, It's still a WIP.

```js
cd your-project
npm i --save "git://github.com/pro-src/cloudscraper.git#ua_randomization"
# The following command will remove node_modules and do a fresh install 
npm ci
```

**Comment by pro-src** [comment]
It works for me on https://subscene.com

Also be sure to add the following:
```js
var cloudscraper = require('cloudscraper').defaults({ gzip: true });
```

**Comment by pro-src** [comment]
@grasssnake123 A little background on the PR is that Cloudflare has a ***ton*** of info on UA's and their respective headers. They added some clever checks to their Anti-Scrape shield and have been updating more recently than ever before. Anyways, we've had to collect some data to fix this properly but a solid solution is almost ready for release.

**Comment by pro-src** [comment]
@grasssnake123 Nvm, don't try that PR right now since some of the responses will be in the Brotli compressed format.

**Comment by pro-src** [comment]
@grasssnake123 The PR is good now, feel free to try it :100:
