### ISSUE TITLE
No error, body returned is cloudflare challenge page.

### ISSUE THREAD

**Issue by roflmuffin** [codemanki/cloudscraper#2]
I am having issues when trying to retrieve a website that is in "I'm under attack mode" (**http://kissanime.com**)

With a very basic cloudscraper.get, no error is returned however the body of the response is the Cloudflare challenge page.

I have noticed this is a sister site to the website currently being investigated in Issue #1, so that might hold some relevance?

Interesting thing to note is that this issue does not occur when using [cloudflare-scraper](https://github.com/Anorov/cloudflare-scrape)

**Comment by roflmuffin** [comment]
Any idea what could be causing this?

**Comment by codemanki** [comment]
@roflmuffin hey. it seems that cloudflare have changed their algo :( i will take a look and fix it asap

**Comment by roflmuffin** [comment]
Alright, I'm afraid I couldn't find another website that was in IUAM so I couldn't really test if it was just this website or the algorithm. I've been trying to look at the changes in [this commit](https://github.com/Anorov/cloudflare-scrape/commit/89562fde84608e5030cde64ea74331b3368ac4fb) where the original python package adapts to the change (on the 19th of March) but I've been having no luck.

**Comment by roflmuffin** [comment]
@codemanki Hey, I finally figured out what the issue was! After I added the new 'pass' parameter to the query string it still wouldn't work and I couldn't figure it out. Turns out we it was using the response headers on the second request rather than the headers used for the original request. 

I've submitted a pull request #3 to merge at your discretion.

Cheers.

**Comment by codemanki** [comment]
@roflmuffin hey :) just answered you here https://github.com/codemanki/cloudscraper/pull/3#issuecomment-104174112 
Closing this issue since @roflmuffin saved the day and fixed it :)
