### ISSUE TITLE
http://www.cineblog01.cc/anime/ returns errorType 3

### ISSUE THREAD

**Issue by cagnulein** [codemanki/cloudscraper#20]
as subject :)

**Comment by codemanki** [comment]
Looks like CF changed their challenge ;) Investigating

**Comment by codemanki** [comment]
1.3.0 version has been released.

**Comment by kopertop** [comment]
Thanks, I can confirm this worked for me!

**Comment by cagnulein** [comment]
You're great! Thanks man!

**Comment by roflmuffin** [comment]
Thanks for the prompt update, much appreciated.
