### ISSUE TITLE
Fragment identifier is not appended to the JS challenge form's action URI

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#203]
The IUAM JS challenge appends the fragment identifier (#hashtag) of the `window.location` to the form's action URI before submission. Cloudscraper is not currently mimicking this behavior.

Example JS challenge:
```js
window.addEventListener("DOMContentLoaded", function() {
  setTimeout(function() {
    // ... document.getElementById("jschl_answer").value = Number()
    f.action += location.hash;
    f.submit();
  }, 4000);
}, false);

**Comment by pro-src** [comment]
@VeNoMouS

**Comment by VeNoMouS** [comment]
Interesting... I did see that the other day... but thought nothing of it..

**Comment by VeNoMouS** [comment]
Looking at mitm's / debugging... it doesn't actually send that hash from what I can see...
