### ISSUE TITLE
Cloudflare challenge updated?

### ISSUE THREAD

**Issue by ArnaudPiroelle** [codemanki/cloudscraper#208]
Since this morning : CaptchaError: captcha on v4.0.1

```javascript
var cloudscraper = require('cloudscraper').defaults({
  headers: {
    'Connection': 'keep-alive',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Language': 'en-US,en;q=0.9'
  }
});
var uri = 'https://www.japscan.to';
cloudscraper.get(uri, function (error, response, body) {
  if (error) {
    throw error;
  }
  console.log(body);
}); 
```

error:
```javascript
node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^
CaptchaError: captcha
```

**Comment by pro-src** [comment]
@ArnaudPiroelle It's the headers that you're using. Cloudflare has improved their browser integrity check (BIC) which is the main reason why v4.0.0 came so quickly. If you use the default headers, meaning don't override, Cloudscraper works just fine. UA randomization was tricky but we've got you covered in v4.0.0. :tada: If you want brotli support on nodejs versions prior to v11: `npm install --save brotli`. If you want bulletproof header then you want brotli support. Good luck!

**Comment by ArnaudPiroelle** [comment]
Indeed! I upgrade node to v12 and it's works...
Thanks ;)
