### ISSUE TITLE
Improve CAPTCHA support by implementing PrivacyPass

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#209]
https://privacypass.github.io/
https://www.petsymposium.org/2018/files/papers/issue3/popets-2018-0026.pdf

> For example, Privacy Pass is supported by Cloudflare to enable users to redeem passes instead of having to solve CAPTCHAs to visit Cloudflare-protected websites.

https://support.cloudflare.com/hc/en-us/articles/115001992652-Can-I-use-Privacy-Pass-with-Cloudflare-

> The extension generates 30 tokens for each CAPTCHA solution and thus can be used to reduce CAPTCHA pages for each user by a similar factor. 

Outdated but from one of Cloudflare's github repos: https://github.com/cloudflare/challenge-bypass-specification/blob/master/captcha-bypass-internet-draft.txt

Browser add-on source: https://github.com/privacypass/challenge-bypass-extension

@VeNoMouS

**Comment by grasssnake123** [comment]
@pro-src 
How to make use this PrivacyPass with cloudscraper?
I am using version  v4.0.1 and meanwhile all are working good.
But it seems like the wack-a-mole game with cloudflare team going faster chase each other. 
I am looking for a more permanent solution.

**Comment by pro-src** [comment]
> How to make use this PrivacyPass with cloudscraper?

Read the links. It's something that we would have to implement. It's not something to be used with Cloudscraper.

> I am using version v4.0.1 and meanwhile all are working good.

Glad to hear it. :+1:

> But it seems like the wack-a-mole game with cloudflare team going faster chase each other.

I have no proof of such, although you might be correct.

> I am looking for a more permanent solution.

I think CF has been a big proponent of PrivacyPass from the beginning. I don't think they would break that so maybe forcing a CAPTCHA, using a service such as anti-captcha.com to solve the initial challenge, and with PrivacyPass implemented, might be the best permanent solution.

The reCAPTCHA challenge hasn't changed at all and the anti-bot code on those pages isn't even being validated server side. Whereas the JS challenge has changed 3-4 times within the past couple of months. However, there has been changes that affect both of those challenge types and some pretty tricky ones that aren't causing problems for everybody yet. By everybody I mean, this project seems to be unaffected.

I things will eventually calm down. Just stick it out with us while we develop new ways to bypass CF.

**Comment by pro-src** [comment]
The browser extension code is really nice and doesn't need to be reproduced for this project. I'll release a modified version that pulls in the reusable parts of the browser-extension and bundle it with the necessary adaptions. Cloudscraper can think list it as a peer dependency and perform an optional require to make use of it. So it is something *to be used with cloudscraper* since we don't want to reproduce and maintain a complete fork.

@codemanki How does that sound to you?

**Comment by codemanki** [comment]
@pro-src sounds very cool!

**Comment by pro-src** [comment]
I'm working on it now and making great progress! A little background on the PrivacyPass core team, they are all cryptographers, one is a Golang core developer for Google, and at least one is a developer for Cloudflare. So it is a promising project indeed.

Since the tokens are blinded and can be redeemed for domains other than the one used to obtain them, it's possible to make an initial request to https://captcha.website to solve and get tokens to redeem for any domain! https://captcha.website is dedicated to the PrivacyPass project.

**Comment by pro-src** [comment]
I'll have this working soon without a single change to cloudscraper. Just taking my time. :smiley:

```js
const cloudscraper = require('cloudscraper').defaults({
  requester: require('privacy-pass')
});
```

**Comment by pro-src** [comment]
I haven't finished this yet but when I get around to it, there is little left that needs to be done. Since no changes need to be made to cloudscraper, this is not a cloudscraper issue. I will update this issue upon publishing the node-privacy-pass package.

**Comment by pro-src** [comment]
I don't know how many people were looking forward to the node-privacy-pass but if the thumbs are any indication, I'm not disappointing too many people. I've changed my mind after putting it off a lot lately. I don't currently plan to finish developing it.
