### ISSUE TITLE
Question: is it possible to return the form values?

### ISSUE THREAD

**Issue by bert-w** [codemanki/cloudscraper#213]
The cloudflare protection page makes a GET request to a `/cdn-cgi/l/chk_jschl` endpoint, is it possible to catch all key/values that are sent to this endpoint and return them, instead of making the actual request?

I'm looking for a library that can execute and solve the Cloudflare protection challenge, but I need the return values myself since I do the HTTP requests itself in PHP.

**Comment by pro-src** [comment]
Hi @bert-w,

The code below allows you to create your own requests and responses for Cloudscraper to use. We only officially support `request` and `request-promise` as the requester so I can't promise that the code below won't need to be updated for a future release.

You'd use it like so:
```js
const cloudscraper = require('cloudscraper').defaults({
  requester: require('./my-requester')
});
```

<details><summary>my-requester.js (es6/es7)</summary>

```js
import { EventEmitter } from 'events';
import { URL } from 'url';
// `npm i --save caseless` although it's available if `request` is installed
import caseless from 'caseless';

export default function (options) {
  return new Request(options);
};

class Request extends EventEmitter {
  constructor (options) {
    super();
    const self = this;

    // All of the properties that I defined are required...
    self.uri = typeof options.uri === 'string'
      ? new URL(options.uri) : options.uri;

    // Use options.headers if need to serialize...
    self.headers = caseless(options.headers);

    // Cloudscraper will only call `request.callback` for the very last request
    self.callback = options.callback;

    // The query string aka form values will be an object
    if (options.qs) {
      console.log(JSON.stringify(options.qs, null, 2));
    }

    // Perform the actual request and emit any events
    if (undefined !== void 0) {
      self.emit('error', new Error('Request error'));
    }

    const body = Buffer.from('Response content', 'utf-8');
    const status = 200;
    const headers = {
      // Response headers
    };

    // Create a response object that `request` normally provides
    const response = new Response(headers, status, body);
    response.request = self;

    // Advanced, update the cookie jar, use `tough-cookie` if needed
    if (response.caseless.has('set-cookie')) {
      options.jar.setCookie(
        response.caseless['set-cookie'],
        self.uri.href,
        { ignoreError: true }
      );
    }

    // Emit the complete event
    setImmediate(() => self.emit('complete', response, response.body));
  }

  getHeader (name) {
    return this.headers.get(name);
  }

  setHeader (name, value) {
    this.headers.set(name, value);
  }
}

class Response {
  constructor (headers, statusCode, body) {
    this.headers = headers;
    this.caseless = caseless(headers);
    this.statusCode = statusCode;
    this.body = body;
  }
}
```
</details>

While I did run this code to ensure that the snippet works, I do not plan on supporting it, it's a DIY thing.
The above code is a contribution to this project and falls under it's MIT license so feel to use/modify/sell.

You can simplify the code for your use case slightly if you want to just emit an error after you have everything that you need.

**Comment by pro-src** [comment]
@bert-w It's probably better to use Cloudscraper to perform the Cloudflare challenge specific requests and use the cookies in your PHP app: https://github.com/codemanki/cloudscraper/issues/210
