### ISSUE TITLE
ReCaptcha error reference

### ISSUE THREAD

**Issue by elpaxel** [codemanki/cloudscraper#217]
Sorry for the issue it's not about this great library.
My question:
Lets assume I got the g-recaptcha-response and sent it with captcha.submit()
And if there is some problem with g-recaptcha-response token HOW can I see it ?
There is errors like timeout, duplicate etc.
Because I made some recaptcha solver and there is the steps that I do:
1. Rendering captcha with sitekey regarding to website hostname. ALL IS GOOD.
2. Solving the captcha ALL IS GOOD.
3. Getting g-recaptcha-response ALL IS GOOD.
4. Sending g-recaptcha-response with captcha.submit() ALL IS GOOD.
BUT I'm getting another captcha after solved immediately. So I'm assume that there is some error with "validation" of g-recaptcha-response.
I know that solving the recaptcha "not exact science" but some more info will be good addition.

P.S. My method based on changing the "http://" on custom protocol and intercepting it. But I don't think that this is the main problem because I'm successfully rendering the captcha without HOSTNAME==SITEKEY errors.

**Comment by pro-src** [comment]
Sup @elpaxel 

> And if there is some problem with g-recaptcha-response token HOW can I see it ?

:thinking: If using cloudscraper, it's possible to return an error in the handler by calling `captcha.submit(error)` or by returning a promise that is rejected at some point.  If a promise is returned in the handler, it's no longer necessary to call `captcha.submit`. If the error is reported in the handler, it can be caught whenever a request is made: `cloudscraper.get('https://example-site.dev').catch(console.error)`

> I know that solving the recaptcha "not exact science" but some more info will be good addition.

I think I could be of more help if the info of interest is elaborated on.

> P.S. My method based on changing the "http://" on custom protocol and intercepting it. But I don't think that this is the main problem because I'm successfully rendering the captcha without HOSTNAME==SITEKEY errors.

I'm not sure that I fully understand.

**Comment by elpaxel** [comment]
> If using cloudscraper, it's possible to return an error in the handler by calling captcha.submit(error) or by returning a promise that is rejected at some point. If a promise is returned in the handler, it's no longer necessary to call captcha.submit. If the error is reported in the handler, it can be caught whenever a request is made: cloudscraper.get('https://example-site.dev').catch(console.error)

Maybe I don't understand something but captcha.submit(error) returns MY error. So if I want to abort captcha sending I will just captcha.submit("MY CUSTOM ERROR"). But I'm talking about error that website will send if g-recaptcha-response is "broken". Because now if g-recaptcha-response is broken all that I will get is another captcha from the website without any explanation why. And I'm not fully sure that cloudflare is returning some info at all so just asking there :)

> I think I could be of more help if the info of interest is elaborated on.

I'm using slightly modified\cleaned version of this: [https://github.com/TheLastTech/NodeJSCaptchaHarvestTime](url)
It's electron app that creates "cap://" protocol. And intercepts g-recaptcha-response after captcha solving.
So normally Google will write error about wrong HOSTNAME at the captcha rendering (sitekey check). But with this "juke" with protocol all is rendering good. So that the question can the custom protocol be the problem ? (Because recaptcha documentation saying that it checks hostname and nothing about protocol)

I have another workaround with ./etc/hosts file manipulation that working fine. So I'm 90% sure that problem in custom protocol but still hoping that its not :)

P.S. Really sorry for my eng :(

**Comment by elpaxel** [comment]
Some updated info that I have found. Maybe someone struggling like me.
If you take captcha for https://example.com and then open it in Electron with custom protocol like cap://example.com, Google will not throw you "Invalid domain for site key" (actually you can even paste any domain different from original) but as I guess (after some testing) g-recaptcha-response will be incorrect\malformed.

**Comment by pro-src** [comment]
Hey @elpaxel 

I haven't forgot. Basically you're using a custom protocol handler in chrome to manipulate those specific requests and you're wondering if that's the problem. I'm not sure that the protocol scheme is to blame for this or not either. I'm also not sure if there's anyway to know that the `g-recaptcha-response` was bad from the client's end except for when you get another CAPTCHA. I'll try to get around to checking this out soon so I can answer more informatively.

**Comment by pro-src** [comment]
AFAIK, The only way to know that the g-recaptcha-response was bad is whether or not you get another CAPTCHA. This is based on what I've observed when testing.
