### ISSUE TITLE
Use within puppeteer?

### ISSUE THREAD

**Issue by gdoron** [codemanki/cloudscraper#220]
Hi,

Is it possible somehow use this library with puppeteer?
If not, are you aware of a way to bypass cloudflare with puppeteer?

Thanks,
Doron

**Comment by elpaxel** [comment]
Sorry If I'm wrong but when I'm using puppeteer it already can "pass" through the cloudflare redirects without any problem. You need only to wait the page to load completely.

**Comment by luminous8** [comment]
I have the same issue, with puppeteer on https://angel.co I got a 403 from cloudflare with a captcha. 
So I'm wondering if we could use this library with puppeteer?
