### ISSUE TITLE
challengeId (jschl_vc) extraction failed

### ISSUE THREAD

**Issue by elpaxel** [codemanki/cloudscraper#221]
challengeId (jschl_vc) extraction failed

**Comment by pro-src** [comment]
There was a car crash somewhere on planet earth. Do you mind helping me narrow it down just a tad?

What version are you using?
The URL and/or page source?
Code snippet?
etc..?

**Comment by elpaxel** [comment]
Uhm sorry I was thinking that library needs to be updated but error is gone.
