### ISSUE TITLE
Cloudflare error 1020

### ISSUE THREAD

**Issue by ikozehh** [codemanki/cloudscraper#222]
I have a problem when sending a post request, I seem to be getting a 1020 cloudflare error and can't find much information regarding the error?
Here is the request
`  return new Promise((resolve, reject) => {
        console.log(hashKey);
        console.log(requiredVar);
        cloudscraper.post({
          uri : directAddress,
          form : {
            token : hashKey,
            chosen_attribute_value : requiredVar,
            'returnHtmlSnippets[partials][0][module]' : "product",
            'returnHtmlSnippets[partials][0][path]' : '_productDetail',
            'returnHtmlSnippets[partials][0][partialName]' : "buybox"
          },
          proxy : proxy,
          resolveWithFullResponse:true
        }).then(body => {
          console.log(body);
          bodyParsed = JSON.parse(body);
          console.log(bodyParsed);
        }).catch(e => {
          console.log(e);
          console.log("error " + e);
          proxy = getRandomProxy();
          //setTimeout(precart, delayTime, hashKey);
        })
      }`

I have tried making the request without proxies, I have double checked the form data and everything seems to be correct?

**Comment by pro-src** [comment]
Hi @ikozehh,

You're being blocked due to custom firewall rules configured by the site owner. It anybody's guess what the rule(s) might be that is causing this problem for you.

https://community.cloudflare.com/t/community-tip-fixing-error-1020-access-denied/66439

> While visiting a site protected by Cloudflare, error 1020 “Access denied (Error: 1020)” indicates you’ve violated a Firewall Rule. When this happens, you’ll see the error “Access Denied (Error: 1020)” and your request was blocked by the filter based Firewall rule on the site. If you’re the site owner, you can find the requests that was blocked by the Firewall on the Firewall page under the Events menu.

If provided a URL, I might be able to tell you how to bypass it.

**Comment by ikozehh** [comment]
Hey thanks for the quick reply
The URL is https://www.bstn.com/p/nike-air-force-1-07-premium-2-at4143-101-111803
Should return a JSON body
Thank you

**Comment by pro-src** [comment]
Here ya go:
```js
const cloudscraper = require('.');
const querystring = require('querystring');
const headers = Object.assign(cloudscraper.defaultParams.headers);
const jar = cloudscraper.defaultParams.jar;

cloudscraper.debug = true;

const uri = 'https://www.bstn.com/en/nike-air-force-1-07-premium-2-at4143-101-111803';
// Visiting the page to similuate real user behavior and to get cookies
cloudscraper.get({ uri, headers }).then(body => {
  // Log the cookies, should have `x-token` now
  console.log(jar);

  let token;
  jar.getCookies(uri).forEach(cookie => {
      if (cookie.key.startsWith('x-token')) {
          token = cookie.value;
      }
  })

  if (!token) throw new Error('Failed to get token');
  // Updating to headers to reflect the previous request
  Object.assign(headers, {
    'Referer': uri,
    // This request is normally made via XHR, let's blend in.
    'X-Requested-With': 'XMLHttpRequest'
  });

  // Parsing the exact form data that the browser sent
  const qs = querystring.decode('token=19ae76f88e7d92ae5f470d32e512738f&chosen_attribute_value=10_407&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5Bmodule%5D=product&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5Bpath%5D=_productDetail&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5BpartialName%5D=buybox')
  // Updating the token for this request
  qs.token = token;

  console.log('FormData:', JSON.stringify(qs, null, 2));

  // The server sends the JSON with HTTP status 302 so disable automatic redirects
  // The request is not simple since it can end with a non-2xx response
  var options = { uri, headers, formData: qs, json: true,
    followRedirect: false, followAllRedirects: false, simple: false };

  return cloudscraper.post(options)
    .then(body => {
        // The body would be parsed as JSON already but the response has a mixed content body
        // There is a html based redirect before the JSON body that needs to be removed
        // Find where the JSON starts and parse from that point
        body = JSON.parse(body.substr(body.indexOf('{')))
        // Finally log the parsed JSON
        console.log('JSON:', JSON.stringify(body, null, 2));
    }).catch(console.error);
}).catch(console.error);
```

**Comment by pro-src** [comment]
@ikozehh You might have not seen this since I forgot to @mention you. Did that do the trick?

**Comment by ikozehh** [comment]
@pro-src Its having problems getting the x-token cookie, more times than not it fails to get the token then occasionally it gets it

**Comment by pro-src** [comment]
I'm not sure why that would be but I think the token can also be parsed from the initial response body by using regex. I'm glad that you got everything working with Cloudscraper. Now you just need to adapt the code. :)

**Comment by ikozehh** [comment]
Yes I have the correct token now but I am still getting the cloudflare 1020 error, did you not get the error when you tested with your code?

**Comment by pro-src** [comment]
I just realized what the problem might be if you're using my exact code snippet in a loop. The `X-Requested-With: XMLHTTPRequest` header is not being unset. You'll want to imitate legitimate browser traffic by including/omitting the correct headers depending the request being made.

> Yes I have the correct token now but I am still getting the cloudflare 1020 error, did you not get the error when you tested with your code?

No, I never received that error for the provided URL. The problem is site specific so I can't really say unless I see the exact code and requests that are being used.

**Comment by ikozehh** [comment]
The problem was really simple actually, I included your code where the headers are updated because the request is made with XHR, but I didnt include the headers option in the post request so I wasn't actually using the headers. Very stupid mistake, have learnt a lot from you and really appreciate all the help you gave me :)

**Comment by pro-src** [comment]
I could have made the same mistake. I'm glad that you figured it out and you're very welcome.
