### ISSUE TITLE
Did Cloudflare update the IUAM challenge?

### ISSUE THREAD

**Issue by ProGamer13** [codemanki/cloudscraper#226]
Cloudflare updated UAM
Error: Unhandled rejection CaptchaError: captcha

**Comment by pro-src** [comment]
Hi @ProGamer13,

* What version of Cloudscraper are you using?
  - `node -p 'require("cloudscraper/package.json").version'`
* Please share the process information:
  - `node -p process`
* When did the problem start occurring?
* How often does the problem occur?
* What is the URL?
* _Please share a minimal working code snippet that reproduces the problem._

**Comment by codemanki** [comment]
@pro-src  we should make your comment as a default issue template :)
