### ISSUE TITLE
Error: tunneling socket could not be established

### ISSUE THREAD

**Issue by dpalade06** [codemanki/cloudscraper#236]
I've been trying to use this library to send get requests to CloudFlare protected websites using some http / https proxies.

For some reason I keep getting errors like:
- RequestError: Error: tunneling socket could not be established, cause=socket hang up
- RequestError: Error: tunneling socket could not be established, cause=connect ECONNREFUSED
- RequestError: Error: tunneling socket could not be established, cause=read ECONNRESET
- RequestError: Error: tunneling socket could not be established, statusCode=503

What exactly am I doing wrong? 

```js

var options = {
	uri: args['url'],
	jar: request.jar(),
	proxy: 'http://' + s_proxy,
	headers: {
		'Connection': 'keep-alive',
	  	'User-Agent': uas[Math.floor(Math.random() * uas.length)],
	  	'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
	  	'Accept-Encoding': 'gzip, deflate',
	  	'Accept-Language': 'en-US,en;q=0.9'
	},
	cloudflareTimeout: 5000,
	cloudflareMaxTimeout: 6000,
	followAllRedirects: true,
	challengesToSolve: 3,
	decodeEmails: false,
	gzip: true,
	agentOptions: { ciphers }
};

cloudscraper.get(args['url'] , function (error, response, body) {

  	if (error) {
    	throw error;
 	}

  	console.log("[+] Request has been sent. (" + s_proxy + ")");

});
```

I even tried setting the proxy env variables, but no luck.

**Comment by pro-src** [comment]
Hi @dpalade06,

The proxies are the problem 90% of the time.
For example:
> RequestError: Error: tunneling socket could not be established, statusCode=503

Looks like the proxy server hung up because of Cloudflare's response status code. Either way, it's a server error code. The problem is on their end.

Have a look at https://github.com/codemanki/cloudscraper/issues/233#issuecomment-510342262 for an example and tests.

Cheers

**Comment by pro-src** [comment]
https://github.com/codemanki/cloudscraper/issues/234
