### ISSUE TITLE
Proxies always throw errors

### ISSUE THREAD

**Issue by GoogleSites** [codemanki/cloudscraper#237]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - 4.1.2 (latest)
  * What version of Node.js are you using? (Please share the process information)
    process {
  title: 'C:\\Windows\\system32\\cmd.exe - node  -p process',
  version: 'v11.8.0',
  versions:
   { node: '11.8.0',
     v8: '7.0.276.38-node.16',
     uv: '1.25.0',
     zlib: '1.2.11',
     brotli: '1.0.7',
     ares: '1.15.0',
     modules: '67',
     nghttp2: '1.34.0',
     napi: '4',
     llhttp: '1.0.1',
     http_parser: '2.8.0',
     openssl: '1.1.0j',
     cldr: '34.0',
     icu: '63.1',
     tz: '2018e',
     unicode: '11.0' },
  arch: 'x64',
  platform: 'win32',
  release:
   { name: 'node',
     sourceUrl:
      'https://nodejs.org/download/release/v11.8.0/node-v11.8.0.tar.gz',
     headersUrl:
      'https://nodejs.org/download/release/v11.8.0/node-v11.8.0-headers.tar.gz',
     libUrl:
      'https://nodejs.org/download/release/v11.8.0/win-x64/node.lib' },
  argv: [ 'C:\\Program Files\\nodejs\\node.exe' ],
  execArgv: [ '-p', 'process' ],
  * When did the problem start occurring?
    When I started using it.
  * How often does the problem occur?
    Every time I use a proxy. Every proxy I use is checked against multiple proxy checkers so they work 100% (they also work when using http)
  * What is the URL?
    https://api.ipify.org?format=json
  * Are there any similar issues? (Please share the links)

- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
const cloudscraper = require("cloudscraper");

cloudscraper({
    method: "GET",
    uri: "https://api.ipify.org?format=json",
    proxy: "http://138.68.173.29:8080"
}).then((res, err) => {
    if (err) throw err;
    if (res) {
        console.log(res);
    }
});
```
</details>

**Comment by pro-src** [comment]
Hi @GoogleSites,

We've been getting a lot of issues about proxies not working. Not all proxies have this problem.

If it does have something to do with the client, the problem is with `request`. Please open an issue there since this library is just a wrapper around `request`. The following code has the same problem.

```js
const request = require("request-promise");

request({
    method: "GET",
    uri: "https://api.ipify.org?format=json",
    proxy: "http://138.68.173.29:8080"
}).then((res, err) => {
    if (err) throw err;
    if (res) {
        console.log(res);
    }
});
```

If you'd like to test proxies yourself, take a look at: https://github.com/codemanki/cloudscraper/issues/233#issuecomment-510342262

These results are for https://api.ipify.org?format=json
```
pass: http://196.27.105.156:53281
pass: http://125.123.18.156:9000
pass: http://193.77.45.19:21776
fail: http://89.28.53.42:8080
pass: http://195.55.108.26:3128
pass: http://185.137.91.1:54895
pass: http://2.139.187.123:3128
pass: http://134.35.241.161:8080
pass: http://95.65.45.69:80
pass: http://181.220.68.106:8080
pass: http://181.44.133.155:8080
fail: http://103.253.146.90:80
fail: http://89.212.7.87:80
pass: http://164.77.134.13:8080
pass: http://101.255.125.10:8080
pass: http://181.27.62.122:8080
pass: http://118.173.232.68:35573
pass: http://118.173.233.149:45160
pass: http://181.191.98.220:8080
pass: http://180.253.36.108:8080
fail: http://180.250.198.138:8080
pass: http://200.54.247.98:8080
pass: http://103.70.145.207:41423
pass: http://218.49.231.153:8080
pass: http://181.115.185.42:8080
fail: http://117.191.11.110:8080
pass: http://180.254.96.218:8080
fail: http://150.95.151.68:8181
fail: http://150.95.151.68:8288
fail: http://150.95.151.68:8184
fail: http://122.152.138.139:80
```

Cheers

**Comment by pro-src** [comment]
https://github.com/codemanki/cloudscraper/issues/234
