### ISSUE TITLE
Refactored to use superagent

### ISSUE THREAD

**Issue by DVassilev** [codemanki/cloudscraper#24]
@codemanki How could this be changed to use superagent instead of request? Thanks.

**Comment by codemanki** [comment]
@DVassilev probably nohow :( This package fully depends on request

**Comment by DVassilev** [comment]
@codemanki so it can't be done just by using something like XMLHTTPREQUEST?

**Comment by codemanki** [comment]
@DVassilev what do you mean? how what you need can be achieved by XMLHTTPREQUEST ?

**Comment by firatbaran** [comment]
How we using this library in c#? (Winforms)

**Comment by codemanki** [comment]
@firatbaran unfortunately you can't use this library with C# as it this javascript and node and not .net

**Comment by ferhatbalaban** [comment]
So, is that impossible to use .net project to pass cloudflare?
And dou provide code sample that is in the sample project?

**Comment by codemanki** [comment]
@ferhatbalaban no, unfortunately you can't use node.js in .net project
