### ISSUE TITLE
Sucuri WAF - Undocumented Code

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#240]
I mentioned this before when I wasn't sure how the code was Cloudflare related. The following code is for bypassing https://sucuri.net/website-firewall/

https://github.com/codemanki/cloudscraper/blob/c65a95385ca9bbd3490f34589ceaffadfbba62c2/index.js#L453-L475

I think this should be mentioned in the README or removed.

+1 for keeping it around since it's still useful i.e. https://github.com/Anorov/cloudflare-scrape/issues/277 where at least the site is using Cloudflare's DNS, at worst it's behind CF and using Sucuri which could be pretty confusing to users.

**Comment by codemanki** [comment]
🤔 for some reason I thought this was for cloudflare :D I will amend Readme

**Comment by pro-src** [comment]
I just realized a couple of problems with the current code.

* We ignore the response because the server header starts with `Sucuri` instead of `cloudflare`.
* The test fixture we're using is outdated. The most recent Sucuri WAF, cookie setting code, uses an un-nested `location.reload` whereas we only provide a fake `document.location.reload`.
  - https://github.com/codemanki/cloudscraper/blob/c65a95385ca9bbd3490f34589ceaffadfbba62c2/lib/sandbox.js#L37

Everything else is A-ok
