### ISSUE TITLE
POST formdata

### ISSUE THREAD

**Issue by FruitBoi** [codemanki/cloudscraper#244]
Hello, I'm not sure if this is a bug, but whenever I attempt to send a POST request and include form data in the request, the form data is lost somehow.

**Comment by codemanki** [comment]
@FruitBoi could you add more details using this [template](https://github.com/codemanki/cloudscraper/issues/new?assignees=&labels=&template=bug_report.md&title=)? This would help to identify the problem you are having.

**Comment by pro-src** [comment]
As stated, the issue template should be used to open a new issue. Closing...
