### ISSUE TITLE
How to download a file?

### ISSUE THREAD

**Issue by Jebati** [codemanki/cloudscraper#256]
For example this one:
https://www.spigotmc.org/resources/essentialsx.9089/download?version=286847

**Comment by pro-src** [comment]
Sup @Jebati,

Did you forget to README ???

![github com_codemanki_cloudscraper](https://user-images.githubusercontent.com/34285059/63986532-d3103900-cac3-11e9-8300-ce1e06ac8cd4.png)

Examples: https://github.com/codemanki/cloudscraper/tree/master/docs/examples#examples

* https://github.com/codemanki/cloudscraper/blob/master/docs/examples/download.js
* https://github.com/codemanki/cloudscraper/blob/master/docs/examples/download-v2.js

Cheers
