### ISSUE TITLE
Cloudflare Code 1020 - Firewall Detection

### ISSUE THREAD

**Issue by true-zero** [codemanki/cloudscraper#261]
This website (https://sneakersnstuff.com) is some how detecting requests from cloudscraper using a custom firewall rule to block them.

After trying to investigate using Fiddler, my requests were being blocked but only if Fiddler was capturing traffic.
The specific cause being  "HTTPS Decryption" being active after taking a look at the [available expressions for the firewall](https://developers.cloudflare.com/firewall/cf-firewall-rules/fields-and-expressions/) I've come to the conclusion that the rule involves the `ssl` boolean expression.

But I'm not sure where to go from here, since cloudscraper establishes an encrypted connection.

**Comment by pro-src** [comment]
Hi @true-zero,

> This website (https://sneakersnstuff.com) is some how detecting requests from cloudscraper using a custom firewall rule to block them.
> ...
> But I'm not sure where to go from here, since cloudscraper establishes an encrypted connection.

I don't have any problem accessing plain HTTP: http://sneakersnstuff.com

Cloudcraper doesn't force HTTPS. It reuses the protocol scheme of the current request's URI. So, if you're fetching e.g. http://example.com and that site doesn't redirect you to https://example, the connection will remain as plain text.

You can handle redirects manually, all of `request`'s options are supported: https://github.com/request/request#requestoptions-callback

Cheers.

**Comment by true-zero** [comment]
I've tested that out and it works well for that specific URL but when I navigate to:

http://www.sneakersnstuff.com/en/2/sneakers?orderBy=Published&skip_layout=true&view_override=_ajax-filter

The request gets 1020'd again.

**Comment by pro-src** [comment]
1020 ????

I get a reCaptcha when using my web browser... It's not a Cloudscraper problem, It's a reCaptcha.
