### ISSUE TITLE
Create typescript definition file

### ISSUE THREAD

**Issue by lillem4n** [codemanki/cloudscraper#265]
Pretty please :)

**Comment by pro-src** [comment]
Sure.

**Comment by codemanki** [comment]
I'm not very familiar with typescript, could you please provide an example of such file?

**Comment by pro-src** [comment]
Endless examples: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by lillem4n** [comment]
Simplest form to help typescript developers not getting a compile error is just to add an index.d.ts file containing:

```typescript
declare module 'cloudscraper';
```

However, a good type definition would of course be king. :)
