### ISSUE TITLE
CloudflareError 1020, Access denied (Custom Firewall Rules)

### ISSUE THREAD

**Issue by zahiid** [codemanki/cloudscraper#266]
Yesterday cloudscraper stopped working on one of my machines meanwhile it is still working on my other computers. I'm using cloudscraper to post data to this url http://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey.
Any idea why this module would work on a machine and not on another ?

**Comment by pro-src** [comment]
Hi zahiid,

The reason would be TLS or an IP issue. See my comments on TLS in https://github.com/codemanki/cloudscraper/issues/264.

**Comment by Jebati** [comment]
Same problem on https://dev.bukkit.org/projects/pixelprinter/files
-  I work through a proxy, if you go directly from them in a browser, everything works, but not through cloudscraper.

**Comment by pro-src** [comment]
@zahiid, as you're aware, the problem can be system specific. I don't have a problem accessing either of the above URLs when using my residential connection or (Non-VPN) cloud service providers.

@Jebati See my previous comment for a potential solution.

Let us know what you've tried and whether it works sporadically, consistently, or not at all.

Thanks guys.

**Comment by pro-src** [comment]
I'm going to go ahead and close this issue since bug reports should make use of the issue template: https://github.com/codemanki/cloudscraper/issues/new?assignees=&labels=&template=bug_report.md&title=

It avoids us having to ask the same questions over and over again.
I'm not closing the discussion, just the issue.

I look forward to your responses and helping you guys resolve these issues.

**Comment by zahiid** [comment]
Well, I added the cipher string you proposed on  #264 and it works fine for the moment, thanks for your help!

**Comment by pro-src** [comment]
@zahiid That's great! I actually proposed a few different cipher strings. What is your OS/CPU info and which cipher string is working of you?

**Comment by zahiid** [comment]
My os is :
![image](https://user-images.githubusercontent.com/11235677/65702695-5bf6a200-e07b-11e9-881c-4f39a4c561d5.png)
and my cpu is : 
![image](https://user-images.githubusercontent.com/11235677/65702772-7f215180-e07b-11e9-98da-76ef4336b9f0.png)
