### ISSUE TITLE
Cloudflare challenge loop (again)

### ISSUE THREAD

**Issue by elpaxel** [codemanki/cloudscraper#285]
10 min ago I've start getting: "Cloudflare challenge loop" error. I think they updated something.

**Comment by happyday517** [comment]
me too

**Comment by ZeroSkillSamus** [comment]
Thought I was the only one was googling how to fix this for the past 2 hours lol

**Comment by puleeno** [comment]
I have the same issue.

**Comment by kamilkoc-yusufayas** [comment]
same here.

**Comment by ax333l** [comment]
same

**Comment by buihoangvu** [comment]
same

**Comment by drdokk** [comment]
Same issue here, even with @elpaxel's edit

**Comment by codemanki** [comment]
Please update to `4.4.0`

**Comment by KostyaChoporov** [comment]
Looks as it appears again.
