### ISSUE TITLE
is cloudscraper view '&' as '&amp;'?

### ISSUE THREAD

**Issue by rogeraabbccdd** [codemanki/cloudscraper#289]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - `4.4.0`
  * What version of Node.js are you using? (Please share the process information)
    - `10.15.3`
  * When did the problem start occurring? `After update to 4.4.0`
  * How often does the problem occur? `Everytime`
  * What is the URL? `https://steamdb.info/api/ExtensionGetPrice/?appid=730&currency=TWD`
  * Are there any similar issues? (Please share the links)

- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
const cloudscraper = require('cloudscraper')
cloudscraper('https://steamdb.info/api/ExtensionGetPrice/?appid=730&currency=TWD').then((htmlStr) => {
  console.log(htmlStr)
}).catch((err) => {
  console.log(err)
})
```
</details>

**Comment by rogeraabbccdd** [comment]
![Code_ecXOeHkpTa](https://user-images.githubusercontent.com/15815422/69838223-8b997480-128d-11ea-9ff9-990c0a9a167c.png)

**Comment by elpaxel** [comment]
& is &amp; after "HTML entities" encoding. It is nothing to do with cloudscraper itself I guess. Sorry if misunderstood.

**Comment by rogeraabbccdd** [comment]
I know it's HTML entities.
My request returns 400 after updating to 4.4.0, I'm searching all possible reasons.

**Comment by elpaxel** [comment]
Try something like:

    var { URL } = require('url');
    cloudscraper(new URL('https://steamdb.info/api/ExtensionGetPrice/?appid=730&currency=TWD'))...

**Comment by codemanki** [comment]
@rogeraabbccdd your code snipper works fine for me and returns a json. Could you try to use node version `8.11.1` or any other 8?

**Comment by rogeraabbccdd** [comment]
@codemanki same problem after switched to `8.11.1`.
It should not return 
```json
{"success":false}
```
it should return 
```json
{"success":true,"data":{"lowest":{"price":"NT$ 134","discount":50,"date":"June 22, 2018"}}}
```

**Comment by rogeraabbccdd** [comment]
@elpaxel 
```
request.setHeader('host', request.uri.host);
                                          ^
TypeError: Cannot read property 'host' of undefined
```

**Comment by codemanki** [comment]
@rogeraabbccdd 🤔 this exactly what it returns for me:

```
>  node test.js

{"success":true,"data":{"lowest":{"price":"NT$ 134","discount":50,"date":"June 22, 2018"}}}
```

**Comment by rogeraabbccdd** [comment]
I just deployed my app to heroku, eveything works fine wtf 🤔🤔🤔.

**Comment by codemanki** [comment]
@rogeraabbccdd 
![giphy](https://user-images.githubusercontent.com/307008/69869765-1a1dee00-12ae-11ea-9c26-cc71c97af113.gif)
