### ISSUE TITLE
PyJs_LONG_0_ ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

### ISSUE THREAD

**Issue by simonsruggi** [codemanki/cloudscraper#290]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - cloudscraper==1.2.14

  * What version of Node.js are you using? (Please share the process information)
    - v13.2.0
  * When did the problem start occurring?
- On a POST request
  * How often does the problem occur?
- Always
  * What is the URL?

- https://www.starcowparis.com/panier

  * Are there any similar issues? (Please share the links)

- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
PyJs_LONG_0_
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

```
</details>

**Comment by codemanki** [comment]
@simonsruggi could you share the code snippet which is causing the error?
