### ISSUE TITLE
CloudflareError 1020, Access denied (Custom Firewall Rules)

### ISSUE THREAD

**Issue by Syliaz** [codemanki/cloudscraper#297]
* What version of Cloudscraper are you using?
    - v4.5.0
  * What version of Node.js are you using? (Please share the process information)
    - v12.12.1
  * How often does the problem occur?
     Always, it only works with my home ip.
  * What is the URL? `https://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey`
  * Are there any similar issues? (Please share the links)
https://github.com/codemanki/cloudscraper/issues/266
https://github.com/codemanki/cloudscraper/issues/264

- [X] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

Same issue as #266 
I have changed the header, cipher key several times, and the request doesn't work when I change ip

```js
cloudscraper.defaultParams.agentOptions.ciphers = ':!ECDHE+SHA:!AES128-SHA:!AESCCM:!DHE:!ARIA';
```

**Comment by pyrocept** [comment]
I am having the same issue, i tried several things with no success.

**Comment by Syliaz** [comment]
![image](https://user-images.githubusercontent.com/42878294/70430488-37f00d80-1a7b-11ea-969a-673a340d4651.png)

I have this issue too.

**Comment by pyrocept** [comment]
> ![image](https://user-images.githubusercontent.com/42878294/70430488-37f00d80-1a7b-11ea-969a-673a340d4651.png)
> 
> I have this issue too.

I suppose you are using proxys, i have the same issue with them, that's why i dont use them...

**Comment by Syliaz** [comment]
Yes it works without proxy

**Comment by Syliaz** [comment]
@pyrocept add me on discord : Syliaz#1452

**Comment by dwayne-dev** [comment]
@codemanki Will you please tell @Syliaz who I am? He's being retarded.

**Comment by dwayne-dev** [comment]
Like, I wrote the issue template that used to create this issue... C'mon! lol

**Comment by pyrocept** [comment]
> Like, I wrote the issue template that you used to create this issue... C'mon! lol

Lmao, you proposed 250$ to fix the issue for something that is already free... 
Scammer detected

**Comment by Syliaz** [comment]
![image](https://user-images.githubusercontent.com/42878294/71353961-cfc12180-257a-11ea-83dc-96dcef93e2ce.png)

Keep ur private version

**Comment by dwayne-dev** [comment]
Whoa... That's uncalled for... I'm going to kindly ask @codemanki to delete those comments... Not cool at all

**Comment by dwayne-dev** [comment]
If I wouldn't have stepped away from the project. I would delete them myself. So thanks for appreciating my work and privacy.

**Comment by dwayne-dev** [comment]
> Lmao, you proposed 250$ to fix the issue for something that is already free...
> Scammer detected

Not at all. That was a legit business offer and it's free why don't you just go and put the info out then... But you can't so there's that.

**Comment by dwayne-dev** [comment]
Look guys, I loved contributing to this open source project and I want to help every time I see a new issue but it's complicated. I sought to help you privately while earning a little side dough. Like I have quite a few people who keep coming back for more business. Anyways, I find your response upsetting and if you did know who I was then also I find it disrespectful since I've put a lot of time into this project for free for you guys.

**Comment by codemanki** [comment]
Actually @dwayne-dev is the person who almost completely rewrote this library ( many thanks to him for that ) and contributed A LOT to this project. I don't see anything bad about him helping others with complicated cloudflare related projects, as this library only provides basic workarounds while clouflare allows to specify custom logic and rules which require manual investigation and coding.
