### ISSUE TITLE
Getting cloudflare cookies after request is complete

### ISSUE THREAD

**Issue by TadaWasRaped** [codemanki/cloudscraper#299]
Is there a way to get the cloudflare cookies after doing a request? Can't seem to find anything, might be me being retarded

**Comment by codemanki** [comment]
@TadaWasRaped You need to first create custom jar, pass it to the request and after it was made, read from the jar:

https://github.com/codemanki/cloudscraper/blob/master/docs/examples/session-persistence.js#L9

**Comment by codemanki** [comment]
Something like this:
```
let jar = cloudscraper.jar();
cloudscraper = cloudscraper.defaults({ jar});
cloudscraper.get(uri).then(() => console.log(jar));
```
