### ISSUE TITLE
Unhandled rejection CaptchaError: captcha

### ISSUE THREAD

**Issue by DiiSCO** [codemanki/cloudscraper#307]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - `4.5.0'`
  * What version of Node.js are you using? (Please share the process information)
    - `v12.13.1`
  * How often does the problem occur?
Every request
  * What is the URL?
https://play.esea.net/

- [YES] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
cloudscraper.get('play.esea.net/')
```
</details>

**Comment by codemanki** [comment]
Please share the `response.body` because I'm not getting any errors.
