### ISSUE TITLE
Checking before accessing site...

### ISSUE THREAD

**Issue by SFx2018** [codemanki/cloudscraper#311]
since yesterday I have problem with: https://ogusers.com/

my script is crashing at: Checking before accessing OGUsers.
in web browser I see they creating new cookie called: "BLAZINGFAST-WEB-PROTECT"

is it related to cloudscraper or other library?

**Comment by codemanki** [comment]
@SFx2018 it looks like some custom made [ddos protection system](https://blazingfast.io/ddos). I don't think that cloudscraper is capable of bypassing it.
