### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by williamoliveira** [codemanki/cloudscraper#33]
Could this be tweaked to work in the browser also?

**Comment by dfanara** [comment]
I suppose you could write a nodejs app to act as an HTTP proxy, where the proxy itself uses cloudscraper to bypass cloudflare and then serves the content back to the browser.

**Comment by williamoliveira** [comment]
Yeah, I could, I am currently doing the scrapping on backend with cheerio but I am trying to make my app serverless

**Comment by dfanara** [comment]
Are you looking to use it in a specific browser? If you don't have anything specific in mind, you could use http://electron.atom.io/ with Chromium and use cloudscraper to load all of the content to display clientside. You may be able to hook into the electron API to force all of the traffic directly through cloudscraper. 

Also, you could write the NodeJS implementation and run a local instance of the HTTP proxy, however that'd require installing the NodeJS binaries which might not be desirable.

**Comment by williamoliveira** [comment]
That wouldnt work for me, its a normal web application.
I will fork this project and see if I can modify to use axios or something instead of request

**Comment by GoChartingAdmin** [comment]
@williamoliveira Did you make any progress on browser side usage of cloudscraper?

**Comment by williamoliveira** [comment]
Nope, I dropped the project I was working on

**Comment by pro-src** [comment]
These [tests](https://github.com/request/request/tree/master/tests/browser) seem to indicate that `request` has had browser support for years. Use a good bundler such as webpack and everything should work.
