### ISSUE TITLE
function onCaptcha looping

### ISSUE THREAD

**Issue by narra-dev** [codemanki/cloudscraper#331]
* What version of Cloudscraper are you using?
    - `4.6.0` same issue in `4.5.0`
  * What version of Node.js are you using? (Please share the process information)
    - `8.11.4`
  * When did the problem start occurring?
    - Today, but I never tried posting `g-recaptcha-response` before
  * How often does the problem occur?
    - always
  * What is the URL?
    - https:///
  * Are there any similar issues? (Please share the links)
    - [329](https://github.com/codemanki/cloudscraper/issues/327) but they experience it only with POST 
    - [327](https://github.com/codemanki/cloudscraper/issues/327) but they experience it only in `4.6.0`

- [✓] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

<details><summary>Code snippet</summary>

```js
var cloudscraper = require("cloudscraper").defaults({ onCaptcha });;

function onCaptcha (options, response, body) {
  let gRes;
  const captcha = response.captcha;
  console.log('loopcheck');
  //I do manualy solve the captcha and paste a validation token here for testing purposes
  gRes = '03AERD8XrC05QbUdvwuXQURT6uVQ5OyfSzH63VKKNsgJX8whswwK81y_DqO4ncsUjLe4aIG8XrumF43Skbo2RbdA8EnJza-rpebwYwlSk2WQLh1Ylpd2tHlqeXt4b--0hjIXzx9O22BxiuUK0SzePfgHObVishFisOE9mU5qOcdHf6VFStRCUiW6n0oKXCcAkCdqB1a_Vjd6Y4beXyTdsiiCB7_QhVR2zKd8BNtg-miAPR6vo6cYlx6bc';
  captcha.form['g-recaptcha-response'] = gRes;
  captcha.submit();
  }

var options = {
  uri: 'https://marketplace.tf/',
};

cloudscraper.get(options, function(error, response, body) {
  console.log(body);
});
```
</details>

I never get `Cloudflare challenge loop` error but the code never exits out of `onCaptcha` loop.
Here's `siteKey` if you are to try yourself `6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0`

**Comment by TaquitoSlayer** [comment]
yay it’s not just me

**Comment by gmmanonymus111** [comment]
Same with backpack.tf :/
I use 9kw to get the response, but after submiting the captcha, it asks again for a new response.

**Comment by narra-dev** [comment]
in my case there was an error in solving captcha

**Comment by TaquitoSlayer** [comment]
Can you elaborate on your error? This issue is still very much alive.

**Comment by narra-dev** [comment]
> Can you elaborate on your error? This issue is still very much alive.

The error was in my custom api wrapper for captcha solving service. g-res token was corrupted. After I made sure it was passed correctly it started working
