### ISSUE TITLE
Email protection is not parsed by cloudscraper

### ISSUE THREAD

**Issue by Godzil** [codemanki/cloudscraper#41]
On Crunchyroll, they have activated the "email protection" from cloudflare and when I try to scrape some of their webpages I get "[email protected]" instead of the expected text.

Example: http://www.crunchyroll.com/the-idolmster-cinderella-girls-theater#

On that webpage the "DOLM@STER" is seen as an email by cloudflare (that mean their regexp is fabulously wrong) and it screw my scraping because I'm not expecting ton of the javascript they insert for that "protection". 

It would be nice if cloudscraper could detect these insertion and parse them the same as it does for the browser detection.

**Comment by Godzil** [comment]
Haven’t tried on the latest version but I suspect this issue still exist..

**Comment by codemanki** [comment]
@Godzil didn't mean to close it.

**Comment by Godzil** [comment]
I know it was for the stall not to not close it :D

**Comment by pro-src** [comment]
This a deobfuscated version of `/cdn-cgi/scripts/********/cloudflare-static/email-decode.min.js`
Here's a gist of the original: https://gist.github.com/pro-src/1819f43cc272d77596156e0410a74c67#file-email-decode-min-js

```js
console.log(decodeEmail('5118151e1d1c1102051403', 0));
// IDOLM@STER

document.querySelectorAll('a').forEach(function (anchor) {
  var prefix = '/cdn-cgi/l/email-protection#';
  var index = anchor.href.indexOf(prefix);
  if (index !== -1) {
    // Update the anchor's href attribute
    console.log('mailto:' + decodeEmail(anchor.href, index + prefix.length));
  }
});

document.querySelectorAll('.__cf_email__').forEach(function (anchor) {
  var hexStr = anchor.getAttribute('data-cfemail');
  // Replace the anchor with a text node that contains the email
  console.log(decodeEmail(hexStr, 0));
});

function decodeEmail (hexStr, start) {
  var email = '', key = parseInt(hexStr.substr(start, 2), 16);

  for (var codePoint, i = start + 2; i < hexStr.length; i += 2) {
    codePoint = parseInt(hexStr.substr(i, 2), 16) ^ key;
    email += String.fromCharCode(codePoint);
  }

  return decodeURIComponent(escape(email));
}
```

@codemanki We could add a `decodeEmails` boolean (off by default) option. If the response content type is `text/html`, update the `href` attributes and replace anchor elements with the decoded emails.

**Comment by pro-src** [comment]
Cloudscraper would
* Use regex to find anchors with class `__cf_email__`, reverse the simple xor cipher, and replace the entire anchor with the decoded email.
* Use regex to find anchors with a `href` attribute that starts with `/cdn-cgi/l/email-protection#`, reverse the simple xor cipher, and replace the `href` attribute value with the decoded email.

**Comment by pro-src** [comment]
@Godzil What do you mean about a ton of Javascript? The only thing that I see is that they're dynamically replacing text content with anchor elements and scrambling the `href` attributes if there's an `@` symbol. This would only be an issue if you wanted emails? :thinking: Are you a spammer?

**Comment by Godzil** [comment]
No I’m not a spammer, their “email protection” is working so badly that it take absolutely not valid email and screwed some of my scrapping, which cause an issue for the project I’m working on.

**Comment by pro-src** [comment]
It won't be a problem once we merge this PR that I'm working on right now. :smile:

**Comment by pro-src** [comment]
@Godzil You can use this for the time being:
```js
function removeProtection (html) {
  var re = /<([a-z]+)( [^>]*[^/>])\s*>[^<]*?<\/\1>/gi;
  var hrefAttr = / href=['"]?(\/cdn-cgi\/l\/email-protection#([a-f0-9]{4,}))/i;
  var dataAttr = / data-cfemail=["']?([a-f0-9]{4,})/i;
  var node, match, result;

  while ((node = re.exec(html)) !== null) {
    if ((match = node[2].match(hrefAttr)) !== null) {
      result = node[0].replace(match[1], 'mailto:' + decodeEmail(match[2]));
    }
    else if ((match = node[2].match(dataAttr)) !== null) {
      result = decodeEmail(match[1]);
    }

    if (match !== null) {
      html = html.substr(0, node.index) + result + html.substr(re.lastIndex);
      re.lastIndex = node.index + result.length - 1;
    }
  }
}

function decodeEmail (hexStr) {
  var email = '', key = parseInt(hexStr.substr(0, 2), 16);

  for (var codePoint, i = 2; i < hexStr.length; i += 2) {
    codePoint = parseInt(hexStr.substr(i, 2), 16) ^ key;
    email += String.fromCharCode(codePoint);
  }

  // noinspection JSDeprecatedSymbols
  return decodeURIComponent(escape(email));
}
```
