### ISSUE TITLE
where to get the cf_clearance cookie

### ISSUE THREAD

**Issue by Josexv1** [codemanki/cloudscraper#42]
I'm modifying the module to get the **cf_clearance cookie**, but the original web response doesn't have it, it have other cookies but not this one, which is the one needed to get the web without bypassing it again.

In which stage could i get this one?

**Comment by pro-src** [comment]
Are you referering to the `Set-Cookie` response header and getting it via `response.headers`?
Cookies are set on the request not on the response. Try getting the cookies that were used to make the request via `response.request.headers`.

**Comment by codemanki** [comment]
@Josexv1 you can get the cookies from `response.headers['set-cookie']` https://stackoverflow.com/questions/34218141/how-to-get-cookies-from-request-module-in-node-js
