### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by iz8mbw** [codemanki/cloudscraper#46]
Is there the possibility to specify the User Agent when made GET?
If no, can it be implemented?
Thanks

**Comment by thepocp** [comment]
The third argument of a function is an object in which you can send headers. For example:
```
  cloudscraper.get(url, (err, res, body) => {
    if (err) reject(err);
    console.log(body);
  }, {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0'
  });
```
