### ISSUE TITLE
Shared jar

### ISSUE THREAD

**Issue by Goswinus** [codemanki/cloudscraper#48]
Hi,

First of all: thanks for a great job! Saved me heaps of time :)
In my project, I need a persistent jar, so I have a small suggestion.

In the first couple of lines, you create a private jar. How about changing this slightly:
    var defaultJar = requestModule.jar();
    var request      = requestModule.defaults({jar: defaultJar}), // Cookies should be enabled

Then, as the first line in function setCookieAndReload:
    var jar = options.jar || defaultJar;

It now uses the (shared) jar from the options, or - if that is not provided - the default (private) jar.
Works like a charm!

Thanks again,
Goswinus

**Comment by pro-src** [comment]
This is supported in the v3.0.0 branch and can be closed.
