### ISSUE TITLE
Usually bypasses this site, but it doesn't anymore.

### ISSUE THREAD

**Issue by Vesporton** [codemanki/cloudscraper#52]
v3rmillion.net

https://pastebin.com/mXXTBYCn

**Comment by Kamikadze4GAME** [comment]
All dont work anymore. I think CloudFlare changed algo

**Comment by Kamikadze4GAME** [comment]
Yeah, i have found smth.
Logic of this package.
1. Get page.
2. If there is CloudFlare challenge try to solve it. If captcha => Error. If all good GOTO 4.
3. Make request with solved challenge.
4. Return response.

And mistake: package get pae, solve challenge and cloudflare give one more page with captcha.
So we need try to find captcha after second request.

From this: 
```js
function giveResults(options, error, response, body, callback) {
  if(typeof options.realEncoding === 'string') {
    callback(error, response, body.toString(options.realEncoding));
  } else {
    callback(error, response, body);
  }
}
```
to this
```js
function giveResults(options, error, response, body, callback) {
  if(typeof options.realEncoding === 'string') {
    body = body.toString(options.realEncoding)
  }

  if (validationError = checkForErrors(error, body)) {
    return callback(validationError, body, response);
  }

  callback(error, response, body);
}
```

**Comment by codemanki** [comment]
@Kamikadze4GAME thanks for looking into this. Gonna fix and push a new versions asap

**Comment by Kamikadze4GAME** [comment]
@codemanki I have wrote you email. Pls answer. Sorry for such message.
