### ISSUE TITLE
Is there support for incapsula?

### ISSUE THREAD

**Issue by jd4ever** [codemanki/cloudscraper#56]
First, thanks for the project!

Would it be possible to integrate incapsula support? It looks like they have similar antiddos strategies and there is also a python library available for bypassing it: https://github.com/ziplokk1/incapsula-cracker-py3

**Comment by codemanki** [comment]
@jd4ever this is a package to bypass the cloudflare, not incapsula. Maybe in future someone could unify multiple providers in one package
