### ISSUE TITLE
Where to paste code in node.js server

### ISSUE THREAD

**Issue by mithlesh425** [codemanki/cloudscraper#61]
I am trying to bypass Bitgo cloudflare which is running on my mannual Server (http://www.rubitcurrency.com/login).
Once I click /login it takes time but nothing happens. For immediate testing purpose I like to know where to paste code that you have written in your Readme.

**Comment by milesalex** [comment]
You can write this in any node environment. Create an app on your computer and install the package, require it, and then run it with `node myfile.js`
