### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by altinselimi** [codemanki/cloudscraper#64]
Hi, I'm trying to cache the requests but sending the 'Cache-Control' header doesn't seem to have any effect. Here's the code:
```
cloudscraper.request(
			{
				method: "GET",
				url: link,
				encoding: null,
				headers: {
					"content-type": "image/jpeg",
					"Cache-Control": "max-age:31556926"
				}
			},
```

**Comment by pro-src** [comment]
Hi @altinselimi ,

The headers must be passed as the third argument.
Example:
```js
cloudscraper.get(uri, callback, headers);
```

This is not the case for the currently unpublished v3.0.0 branch, your code works as is on that branch.
This can be closed.
