### ISSUE TITLE
Put parsing related code into it's own file

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#80]
This is sorta mentioned as a TODO in the README.md
> Expose solve methods to use them independently

This would help modularize things a bit and aid people looking for browser support. The idea is to make the parsing code independent of [request](https://github.com/request/request). This would allow the tree shaking feature of popular bundlers to remove the `request` dependency altogether.

**Comment by codemanki** [comment]
@pro-src i want to take care of this one if you don't mind

**Comment by pro-src** [comment]
@codemanki, for sure. :muscle:

**Comment by codemanki** [comment]
@pro-src so let's maybe split the tickets between us, so you don't work alone? Maybe you could comment on the issues you want to work on, and the ones that you leave for me?

**Comment by pro-src** [comment]
@codemanki, cool, to add to that, if they're assigned to you, I'll leave it for ya. I plan on helping to close the current issues and taking a second glance at stream support before I go back to the project that depends on cloudscraper. I've enjoyed working on this a lot. If you need me to tackle any issue, just can just assign me an issue. :100:

**Comment by codemanki** [comment]
@pro-src  awesome :) thank you again for your work and time! I feel now more motivated to continue working on cloudscraper and gonna add requested by the community features

**Comment by pro-src** [comment]
@codemanki I'm going to maintain a fork of cloudflare-scrape that will depend on this package. The idea is to keep this package as submodule in my fork: https://github.com/pro-src/cloudscraper.py and exclude the libs that aren't needed for parsing in the published package. This should work great so long as I don't have to include any of cloudscraper's dependencies. Although, I guess I could use some bundler to perform tree-shaking as a build step. I'd really appreciate it if you'd keep that in mind when implementing this feature. Thanks

**Comment by pro-src** [comment]
@codemanki So this looks great: https://pypi.org/project/cloudscraper/ but is still in the planning phase ofc. Have you made any progress on this? I don't mind sending a PR if you don't have the time. Anyway, I'm looking forward to bringing these two projects together.

**Comment by codemanki** [comment]
@pro-src I'm a bit busy this week. If you have any work in progress, please feel free to create a WIP PR if you want

**Comment by pro-src** [comment]
I don't mind giving you a few weeks. I'll focus on other issues, circle back, and send a WIP if there's not one already.

**Comment by codemanki** [comment]
@pro-src you would want to use these changes in your project? Maybe you could adjust the name of your project a bit, like `cloudscraperPy` or so, to remove the confusion?

**Comment by pro-src** [comment]
Thats what I've done with the repo. Since it will depend on cloudscraper, I thought it would be less confusing to have the python version of the same name. `cloudscraper.py` !== `cloudscraper.js` but in the code, it's cloudscraper.

**Comment by codemanki** [comment]
@pro-src okay then. Maybe we could crosslink the libraries in the readmes, mentioning python and js versions :)

**Comment by pro-src** [comment]
That's dope.

**Comment by codemanki** [comment]
Then please give me some time to work on this feature.

**Comment by pro-src** [comment]
@codemanki If you wanted to create an organization repository in the future, I could transfer ownership of cloudscraper.py to you.

https://github.com/cloudscraper/cloudscraper
https://github.com/cloudscraper/cloudscraper.py

I would require commit access to `cloudscraper.py` ofc. Just something to thing about.

**Comment by pro-src** [comment]
Also, please keep it in mind that I've already been waiting a month for something that you said you wanted to do. I've been really patient and reaffirmed that by saying that I'll wait for a few weeks. I might be reading a little too deep into it but the response that followed that affirmation.

> Then please give me some time to work on this feature.

Doesn't quite seem right to me. As if I was being impatient. I could send a PR to close this issue in a single day but I'm being considerate. I've already rewritten this entire project many times over and the graphs show that. I'm not trying to be contentious. Just letting you know that I do have a limit. I don't want to send a PR to close this issue. I want to fairly allow you to contribute to your own project. And if I'm being honest, I haven't seen that aside from you merging my PRs. You haven't had the time, it's perfectly understandable. No worries. I'm still happy to be working on this project with you and look forward to closing this issue. But If by some chance, a sense of pride is blocking contributions to this project, I'll be forced to republish. Surely, that isn't the case at all.

**Comment by codemanki** [comment]
@pro-src regarding the comment you made and then removed, I understand your concerns, and I'm sorry for not keeping a lot of attention to fixing things, but as you pointed out I really want to contribute to the project even though I don't have enough time. I will create a PR this week and will try to unblock you asap. Sorry :(

**Comment by pro-src** [comment]
It's understandable. thx for the kind response. If you can't get to it this week, I won't bug you. No worries :)

**Comment by codemanki** [comment]
@pro-src I don't know what to say, but it is not getting better. I'm currently overwhelmed with work and at the end of the day feeling braindead. Sorry for letting you down lately. If you already have this functionality already implemented, please make a PR and i will accept it asap.

**Comment by pro-src** [comment]
You don't have to explain anything to me. That's just typical life. If you want more time, take it. I'm working on some other things right now anyway. But I don't want to impose it on you either. When I come back around to this, I'll check with you before working on a PR.

**Comment by pro-src** [comment]
What parsing related code? We removed almost all of the regex. :rofl: 
We could modularize things a bit more which I've done to some extent in the v4.0.0 PR which made things more testable.
