### ISSUE TITLE
Yet another badge

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#89]
Greenkeeper is a must have as it will send you PR's automatically whenever there is say, a new version of `request/request`. Super easy to setup and I'll send a PR for this if you want it. It only adds a line to the `.travis.yml`. Oh ya, it's free too! So, if you want that: https://greenkeeper.io

Install it: https://github.com/apps/greenkeeper
Ensure it is enabled: https://account.greenkeeper.io/account/codemanki

Best feature is that the PR will trigger CI builds so you'll know immediately if the package version in the PR introduces breaking changes.

Cons: N/A

**Comment by codemanki** [comment]
But why would i use this service if i have `"request": "^2.88.0"` in the package.json? It guarantees that version is always up to date

**Comment by pro-src** [comment]
Build failure notifications

**Comment by pro-src** [comment]
@codemanki, if request was patched to version: `2.88.1`, cloudscraper tests would be ran during a new CI build for that version and we'll automatically know if it breaks because of CI notifications.

This explains it very well: https://blog.greenkeeper.io/greenkeeper-in-a-nutshell-what-it-does-how-it-works-124af9b18945

Also, once you realize how useful this, you might consider not using a caret-version, and include a lockfile. In which case `greenkeeper-lockfile` would automatically update `package-lock.json` etc. It's all about the automation.
