### ISSUE TITLE
Add web crawler functionality

### ISSUE THREAD

**Issue by pro-src** [codemanki/cloudscraper#95]
I don't need the feature personally but I think it'd be nice to have and make the name more fitting.

Something like this: https://github.com/jordanpotti/CloudScraper
<strike>Obviously this would be overkill for this package:</strike> https://github.com/bda-research/node-crawler

Actually, there isn't all that much code in node-crawler, it's primarily just combining other packages...

**Comment by codemanki** [comment]
@pro-src i think if cloudscraper will be flexible and extensible it can be used together with web scrapers and so. I feel it should be just a tool that makes a request and tries to bypass the protection, and nothing more. Maybe also adding a way to solve recaptcha in future

**Comment by pro-src** [comment]
@codemanki Fair enough :smile:
